import {Window} from 'happy-dom';
import {fileURLToPath} from 'node:url';import vm from 'node:vm';import fs from 'node:fs';import assert from 'node:assert/strict';
const root=fileURLToPath(new URL('../static/',import.meta.url));const w=new Window({url:'http://127.0.0.1:8765',settings:{disableCSSFileLoading:true,disableJavaScriptFileLoading:true}});
w.document.write(fs.readFileSync(root+'index.html','utf8').replace(/<script[^>]*>[\s\S]*?<\/script>/g,''));
const ctx=new Proxy({createLinearGradient:()=>({addColorStop(){}})}, {get:(o,k)=>o[k]||(()=>{})});
w.HTMLCanvasElement.prototype.getContext=()=>ctx;
for(const el of w.document.querySelectorAll('canvas')){Object.defineProperty(el,'clientWidth',{get:()=>850});Object.defineProperty(el,'clientHeight',{get:()=>510});el.getBoundingClientRect=()=>({left:0,top:0,width:850,height:510});el.setPointerCapture=()=>{};el.hasPointerCapture=()=>false;el.releasePointerCapture=()=>{}}
w.Option=function(text,value){const o=w.document.createElement('option');o.textContent=text;o.value=value;return o};
w.requestAnimationFrame=()=>0;w.setTimeout=()=>1;w.clearTimeout=()=>{};w.confirm=()=>true;
const fixture=JSON.parse(fs.readFileSync(new URL('ui_fixture.json',import.meta.url)));
w.fetch=async(url,options)=>({ok:true,json:async()=>url.endsWith('/init')?structuredClone(fixture):url.endsWith('/state')?structuredClone(fixture.state):({profile:[],length:0})});
const context=vm.createContext(w);for(const file of ['geometry.js','app.js','elevation.js','editor.js','processing.js'])vm.runInContext(fs.readFileSync(root+file,'utf8'),context,{filename:file});
await w.init();assert.equal(w.document.querySelector('#toast').textContent,'');
let count=0;const check=(name,fn)=>{fn();count++;console.log('PASS '+name)};
check('train profile panel',()=>{assert.ok(w.document.querySelector('#trainSpecs').textContent.includes('C381'));assert.ok(w.document.querySelector('#trainSpecs').textContent.includes('1.3 m/s²'))});
check('initial cockpit HUD and radar',()=>{assert.equal(w.document.querySelector('#cornerNotch').textContent,'N');assert.equal(w.document.querySelector('#cornerSpeed').textContent,'0.0');assert.ok(w.document.querySelector('#radar').innerHTML.includes('青溪'))});
await w.document.querySelector('#classicToggle').onclick();check('classic mode switch',()=>{assert.equal(w.document.querySelector('#classicToggle').getAttribute('aria-checked'),'true');assert.equal(w.document.body.classList.contains('classic'),true)});
await w.document.querySelector('#classicToggle').onclick();check('simple mode restored',()=>assert.equal(w.document.body.classList.contains('classic'),false));
await w.tab('editor');
w.document.querySelector('#drawNew').click();check('new route without stations',()=>assert.equal(w.document.querySelectorAll('#segments tr').length,0));
const canvas=w.document.querySelector('#editOverlay');const ev=(type,x,y)=>canvas.dispatchEvent(new w.PointerEvent(type,{clientX:x,clientY:y,button:0,pointerId:1,bubbles:true}));
ev('pointerdown',200,400);ev('pointermove',500,400);ev('pointerup',500,400);
check('mouse drag creates straight segment',()=>{assert.equal(w.document.querySelectorAll('#segments tr').length,1);assert.equal(+w.document.querySelector('[data-seg="0"][data-key="radius"]').value,0)});
w.document.querySelector('#toolArc').click();w.document.querySelector('#drawRadius').value='5000';ev('pointerdown',500,400);ev('pointermove',700,200);ev('pointerup',700,200);
check('mouse drag creates endpoint/R arc',()=>{assert.equal(w.document.querySelectorAll('#segments tr').length,2);assert.equal(+w.document.querySelector('[data-seg="1"][data-key="radius"]').value,5000)});
w.document.querySelector('#undoEdit').click();check('undo arc creation',()=>assert.equal(w.document.querySelectorAll('#segments tr').length,1));
w.document.querySelector('#redoEdit').click();check('redo arc creation',()=>assert.equal(w.document.querySelectorAll('#segments tr').length,2));
w.document.querySelector('#toolSelect').click();ev('pointerdown',500,400);ev('pointermove',480,350);ev('pointerup',480,350);
check('shared endpoint drag edits length',()=>{assert.notEqual(+w.document.querySelector('[data-seg="0"][data-key="length"]').value,+(300/(410/1200)).toFixed(1));assert.match(w.document.querySelector('#selectionInfo').textContent,/節點/)});
const mid=vm.runInContext('projectMap(G.at(editGeom.pieces[1],editGeom.pieces[1].length/2))',context);
const beforeRadius=+w.document.querySelector('[data-seg="1"][data-key="radius"]').value;
ev('pointerdown',mid.x,mid.y);ev('pointermove',mid.x-25,mid.y-15);
check('arc handle live one-decimal radius',()=>assert.match(w.document.querySelector('#radiusLive').textContent,/R = [0-9]+\.[0-9] m/));
ev('pointerup',mid.x-25,mid.y-15);
check('arc handle changes radius',()=>assert.notEqual(+w.document.querySelector('[data-seg="1"][data-key="radius"]').value,beforeRadius));
w.document.querySelector('#undoEdit').click();
// Re-select the shared endpoint after undo; it is at the previously dragged screen position.
ev('pointerdown',480,350);ev('pointerup',480,350);
w.document.querySelector('#deleteNode').click();check('delete interior node merges edges',()=>{assert.equal(w.document.querySelectorAll('#segments tr').length,1);assert.equal(+w.document.querySelector('[data-seg="0"][data-key="radius"]').value,0)});
w.document.querySelector('#undoEdit').click();check('undo node deletion',()=>assert.equal(w.document.querySelectorAll('#segments tr').length,2));
const limit=w.document.querySelector('#global_limit');limit.value='55';limit.dispatchEvent(new w.Event('change',{bubbles:true}));check('global limit event recomputes rows',()=>assert.ok([...w.document.querySelectorAll('#segments tr')].every(r=>r.textContent.includes('55 km/h')||r.textContent.includes('50 km/h'))));
w.document.querySelector('#undoEdit').click();check('undo global limit field',()=>assert.equal(w.document.querySelector('#global_limit').value,''));
check('auto limit is genuinely blank input',()=>assert.equal(w.document.querySelector('[data-key="limit"]').value,''));
// OSM regression: Leaflet must receive a Point object, never a lat/lng array.
let zoomArgument=null;w.L={point:(x,y)=>({x,y,pointType:true})};
vm.runInContext('mapReady=true;map={getMinZoom:()=>2,getMaxZoom:()=>19,getZoom:()=>14,setZoomAround:(p,z)=>{window.zoomCapture={p,z}}}',context);
const wheel=new w.Event('wheel',{bubbles:true,cancelable:true});Object.defineProperties(wheel,{clientX:{value:450},clientY:{value:250},deltaY:{value:-120}});canvas.dispatchEvent(wheel);
check('OSM wheel passes screen Point instead of geographic array',()=>{assert.equal(w.zoomCapture.p.pointType,true);assert.equal(w.zoomCapture.p.x,450);assert.equal(w.zoomCapture.z,15)});
vm.runInContext('mapReady=false;map=null',context);
w.document.querySelector('#toolStation').click();
const stationPoint=vm.runInContext('projectMap(G.at(editGeom.pieces[0],editGeom.pieces[0].length*.6))',context);
ev('pointerdown',stationPoint.x,stationPoint.y);
check('map station tool inserts blank-arrival station',()=>{assert.equal(w.document.querySelectorAll('#stations tr').length,1);assert.equal(w.document.querySelector('[data-st="0"][data-key="arrival"]').value,'')});
w.document.querySelector('#undoEdit').click();
check('undo map station placement',()=>assert.equal(w.document.querySelectorAll('#stations tr').length,0));
w.document.querySelector('#addStation').click();
const oldFetch=w.fetch;let difficultySent;
w.fetch=async(url,options)=>{if(url.endsWith('/schedule')){const b=JSON.parse(options.body);difficultySent=b.difficulty;const r=structuredClone(b.route);r.stations.forEach(st=>{if(st.arrival==null)st.arrival=180});return{ok:true,json:async()=>({route:r,warnings:[],legs:[]})}}return oldFetch(url,options)};
w.document.querySelector('#scheduleDifficulty').value='precise';
await w.document.querySelector('#autoSchedule').onclick();
check('schedule button sends selected difficulty',()=>assert.equal(difficultySent,'precise'));
check('schedule button displays returned blank-fill time',()=>assert.equal(w.document.querySelector('[data-st="0"][data-key="arrival"]').value,'180'));
w.document.querySelector('#undoEdit').click();
check('undo automatic time fill restores blank',()=>assert.equal(w.document.querySelector('[data-st="0"][data-key="arrival"]').value,''));

check('new station platform defaults to blank',()=>assert.equal(w.document.querySelector('[data-st="0"][data-key="platform"]').value,''));
const platform=w.document.querySelector('[data-st="0"][data-key="platform"]');platform.value='100';platform.dispatchEvent(new w.Event('change',{bubbles:true}));
check('short platform prompts warning',()=>assert.match(w.document.querySelector('#toast').textContent,/月台短於/));
w.document.querySelector('#autoPlatforms').click();
check('bulk automatic platform clears explicit value',()=>assert.equal(w.document.querySelector('[data-st="0"][data-key="platform"]').value,''));
w.document.querySelector('#undoEdit').click();
check('bulk automatic platform undo',()=>assert.equal(w.document.querySelector('[data-st="0"][data-key="platform"]').value,'100'));
w.document.querySelector('#toolOrigin').click();ev('pointerdown',stationPoint.x,stationPoint.y);
check('map origin field set',()=>assert.notEqual(w.document.querySelector('#originCenter').value,''));
let recomputeSent=false;
w.fetch=async(url,options)=>{if(url.endsWith('/schedule')){const b=JSON.parse(options.body);recomputeSent=b.recompute;difficultySent=b.difficulty;const r=structuredClone(b.route);r.stations.forEach(st=>st.arrival=99);return{ok:true,json:async()=>({route:r,warnings:[],legs:[]})}}return oldFetch(url,options)};
w.document.querySelector('#scheduleDifficulty').value='hard';
await w.toggleStop(0);
check('stop switch forces full schedule recompute with current difficulty',()=>{assert.equal(recomputeSent,true);assert.equal(difficultySent,'hard');assert.equal(w.document.querySelector('[data-stop="0"]').getAttribute('aria-checked'),'false');assert.equal(w.document.querySelector('[data-st="0"][data-key="arrival"]').value,'99')});
w.document.querySelector('#undoEdit').click();
check('undo stop switch restores time and stop flag together',()=>{assert.equal(w.document.querySelector('[data-stop="0"]').getAttribute('aria-checked'),'true');assert.equal(w.document.querySelector('[data-st="0"][data-key="arrival"]').value,'')});
w.fetch=async()=>({ok:false,json:async()=>({error:'排時失敗測試'})});await w.toggleStop(0);
check('failed schedule leaves stop setting unchanged',()=>assert.equal(w.document.querySelector('[data-stop="0"]').getAttribute('aria-checked'),'true'));
let directionSent;
w.fetch=async(url,options)=>{if(url.endsWith('/load')){directionSent=JSON.parse(options.body).direction;return{ok:true,json:async()=>({...structuredClone(fixture),state:{...structuredClone(fixture.state),service_direction:directionSent}})}}return oldFetch(url,options)};
await w.document.querySelector('#reverseService').onclick();
check('reverse service button requests backward run',()=>assert.equal(directionSent,'backward'));
await w.document.querySelector('#reverseService').onclick();
check('reverse service button restores forward run',()=>assert.equal(directionSent,'forward'));
w.fetch=oldFetch;

// 0.1.4 HUD, file names, paginated tables and scissors.
w.newState={...structuredClone(fixture.state),target:{...fixture.state.target,stop_enabled:false,name:'台北'},distance:9050};
vm.runInContext('state=window.newState;update()',context);
check('passing beyond 5 km uses 過 label and schedule',()=>{assert.match(w.document.querySelector('#radar').innerHTML,/過 台北/);assert.equal(w.document.querySelector('#scheduleLabel').textContent,'表定通過')});
vm.runInContext('state.distance=2800;update()',context);
check('passing within 5 km uses green marker',()=>assert.match(w.document.querySelector('#radar').innerHTML,/#73db88/));
vm.runInContext('state.target.stop_enabled=true;update()',context);
check('stop uses blue marker and arrival label',()=>{assert.match(w.document.querySelector('#radar').innerHTML,/#66c4ef/);assert.equal(w.document.querySelector('#scheduleLabel').textContent,'表定抵達')});
vm.runInContext("state.skipped_dwell=true;state.doors=true;state.wait=5;state.done=false;state.paused=false;update()",context);
check('skip countdown overlay',()=>{assert.equal(w.document.querySelector('#dwellNotice').hidden,false);assert.match(w.document.querySelector('#dwellNotice').textContent,/已跳過停站時間.*將於5秒後發車/)});
vm.runInContext("state.failure={kind:'derailed'};state.done=true;state.message='列車脫軌';update()",context);
check('failure overlay distinguishes game over',()=>assert.equal(w.document.querySelector('#pauseMask strong').textContent,'遊戲結束'));
vm.runInContext("draft.name='台北測試線';",context);
check('export uses route name',()=>assert.equal(w.routeFilename(),'台北測試線'));
vm.runInContext("draft.name='CON';",context);
check('export sanitizes Windows reserved names',()=>assert.equal(w.routeFilename(),'_CON'));
vm.runInContext("draft.segments=Array.from({length:101},()=>({length:10,radius:0,mode:'ground',offset:0}));segmentPage=0;renderTables()",context);
check('large table renders one page',()=>assert.equal(w.document.querySelectorAll('#segments tr').length,100));
w.document.querySelector('#segmentNext').click();
check('pagination keeps original segment index',()=>{assert.equal(w.document.querySelectorAll('#segments tr').length,1);assert.equal(w.document.querySelector('[data-seg]').dataset.seg,'100')});
vm.runInContext("draft=clone(route);segmentPage=0;selectedSegment=-1;refreshLocal();renderTables()",context);
await w.tab('editor');
const cutPoint=vm.runInContext('projectMap(G.at(editGeom.pieces[0],editGeom.pieces[0].length/2))',context);
const countBefore=vm.runInContext('draft.segments.length',context);
let splitRequested;
w.fetch=async(url,options)=>{if(url.endsWith('/split')){const b=JSON.parse(options.body);splitRequested=b.position;const r=structuredClone(b.route),first=r.segments[0];r.segments.splice(0,1,{...first,length:first.length/2},{...first,length:first.length/2});return{ok:true,json:async()=>({route:r,index:0,position:b.position})}}return oldFetch(url,options)};
await w.cutSegment(cutPoint);
check('scissors split is applied',()=>{assert.ok(splitRequested>0);assert.equal(vm.runInContext('draft.segments.length',context),countBefore+1)});
w.document.querySelector('#undoEdit').click();
check('scissors undo restores segment count',()=>assert.equal(vm.runInContext('draft.segments.length',context),countBefore));
w.fetch=oldFetch;

vm.runInContext("draft={name:'DEM草稿',lat:25,lon:121,heading:0,segments:[{length:1000,radius:200000,mode:'ground'},{length:1000,radius:-200000,mode:'elevated',offset:10}],stations:[{name:'中間站',center:1000,arrival:null}],terrain:[[0,10],[1000,20],[2000,50]]};elevationView=null;refreshLocal()",context);
const elev=w.document.querySelector('#elevation');
const ew=(delta,shift=false)=>{const e=new w.Event('wheel',{bubbles:true,cancelable:true});Object.defineProperties(e,{clientX:{value:440},clientY:{value:180},deltaY:{value:delta},shiftKey:{value:shift}});elev.dispatchEvent(e);};
const epointer=(type,x)=>elev.dispatchEvent(new w.PointerEvent(type,{clientX:x,clientY:180,button:0,pointerId:2,bubbles:true}));
const anchor=vm.runInContext('elevationS(440)',context);ew(-300);
check('elevation wheel zoom keeps cursor chainage anchored',()=>{assert.ok(vm.runInContext('elevationView.span<2000',context));assert.ok(Math.abs(vm.runInContext('elevationS(440)',context)-anchor)<1e-8)});
const startView=vm.runInContext('elevationView.start',context);epointer('pointerdown',440);epointer('pointermove',340);epointer('pointerup',340);
check('elevation drag pans without changing geometry',()=>{assert.ok(vm.runInContext('elevationView.start',context)>startView);assert.equal(vm.runInContext('draft.segments.length',context),2)});
ew(-100,true);check('shift wheel zooms vertical scale',()=>assert.ok(vm.runInContext('elevationView.zScale>1',context)));
epointer('pointermove',500);check('readout displays track terrain grade and chainage',()=>{const text=w.document.querySelector('#elevationReadout').textContent;for(const word of ['里程','軌道','地面','坡度','%'])assert.ok(text.includes(word))});
epointer('pointerdown',500);epointer('pointerup',500);check('profile click selects corresponding route segment',()=>assert.ok(vm.runInContext('selectedSegment>=0',context)));
w.document.querySelector('#elevationReset').click();check('elevation reset restores whole route',()=>{assert.equal(vm.runInContext('elevationView.start',context),0);assert.equal(vm.runInContext('elevationView.span',context),2000)});
ew(100000);check('zoom out is clamped to route bounds',()=>assert.equal(vm.runInContext('elevationView.span',context),2000));
let labels=[],dashes=[];ctx.fillText=text=>labels.push(text);ctx.setLineDash=a=>dashes.push(a);
w.drawElevation();check('station position uses dashed vertical marker',()=>{assert.ok(labels.includes('停 中間站'));assert.ok(dashes.some(a=>a[0]===5))});
console.log(`${count} DOM event checks passed (simulated DOM, not browser rendering)`);
for(let i=0;i<20;i++)await Promise.resolve();

w.newState=structuredClone(fixture.state);
vm.runInContext('state=window.newState;state.speed=state.limit+0.01;update()',context);
check('overspeed HUD immediately red',()=>assert.equal(w.document.querySelector('#cornerSpeed').classList.contains('overspeed'),true));
vm.runInContext('state.speed=state.limit;update()',context);
check('HUD clears red at limit',()=>assert.equal(w.document.querySelector('#cornerSpeed').classList.contains('overspeed'),false));
vm.runInContext('draft=clone(route);fillEditor();window.prependBefore=clone(draft)',context);
w.document.querySelector('#prependLength').value='750';w.document.querySelector('#prependRadius').value='-1500';w.document.querySelector('#prependRoute').click();
check('prepend button moves station chainage',()=>assert.ok(vm.runInContext('Math.abs(draft.stations[0].center-window.prependBefore.stations[0].center-750)<1e-8',context)));
w.document.querySelector('#undoEdit').click();
check('prepend undo restores entire route',()=>assert.ok(vm.runInContext('JSON.stringify(draft)===JSON.stringify(window.prependBefore)',context)));


// 0.1.5 reversible processing workflows.
w.newRoute=structuredClone(fixture.route);
vm.runInContext('draft=clone(window.newRoute);fillEditor()',context);
const processingBase=vm.runInContext('JSON.stringify(draft)',context);
w.fetch=async(url,options)=>{const b=JSON.parse(options.body);const candidate=structuredClone(b.route);candidate.terrain=candidate.terrain.map(([s,z])=>[s,z+10]);candidate.terrain_original=structuredClone(b.route.terrain);return{ok:true,json:async()=>({route:candidate,stats:{before:{max_grade_pct:10},after:{max_grade_pct:1},max_change:10,count:2},warnings:[]})}};
await w.document.querySelector('#previewSmooth').onclick();
check('smoothing preview does not change draft',()=>assert.equal(vm.runInContext('JSON.stringify(draft)',context),processingBase));
check('smoothing review displayed',()=>assert.equal(w.document.querySelector('#processingReview').hidden,false));
w.document.querySelector('#applyProcessing').click();
check('apply processing updates terrain and retains original',()=>assert.ok(vm.runInContext('draft.terrain[0][1]===draft.terrain_original[0][1]+10',context)));
w.document.querySelector('#undoEdit').click();
check('undo processing restores entire draft',()=>assert.equal(vm.runInContext('JSON.stringify(draft)',context),processingBase));
await w.document.querySelector('#previewSmooth').onclick();
vm.runInContext("draft.name='changed while previewing'",context);w.document.querySelector('#applyProcessing').click();
check('stale preview cannot overwrite new edits',()=>{assert.equal(vm.runInContext('draft.name',context),'changed while previewing');assert.match(w.document.querySelector('#processingStatus').textContent,/失效/)});
vm.runInContext('draft=clone(window.newRoute);fillEditor()',context);
await w.document.querySelector('#previewSmooth').onclick();w.document.querySelector('#cancelProcessing').click();
check('cancel preview leaves original',()=>assert.equal(vm.runInContext('JSON.stringify(draft)',context),processingBase));
let uploadedFile=false;
w.fetch=async(url,options)=>{
 if(url.endsWith('/dtm-start'))return{ok:true,json:async()=>({token:'test-token'})};
 if(url.includes('/dtm-upload/')){uploadedFile=options.body instanceof w.File;const candidate=structuredClone(fixture.route);candidate.terrain=[[0,100],[100000,100]];return{ok:true,json:async()=>({route:candidate,metadata:{crs:'EPSG:4326'},count:2,stats:{min_z:100,max_z:100,max_grade_pct:0}})}};
 return oldFetch(url,options);
};
await w.document.querySelector('#dtmFile').onchange({target:{files:[new w.File(['II*','test'],'terrain.tif')],value:'terrain.tif'}});
check('DTM upload sends raw file and remains preview',()=>{assert.equal(uploadedFile,true);assert.equal(vm.runInContext('JSON.stringify(draft)',context),processingBase);assert.match(w.document.querySelector('#processingSummary').textContent,/GeoTIFF/)});
w.document.querySelector('#cancelProcessing').click();w.fetch=oldFetch;

vm.runInContext("draft={lat:25,lon:121,terrain:[[0,100],[50,120],[300,100]],stations:[],segments:Array.from({length:3},()=>({length:100,radius:0,mode:'ground',offset:0}))};fillEditor()",context);
w.document.querySelector('#freezeHeights').click();
check('freeze button retains interior terrain knots',()=>assert.equal(vm.runInContext('draft.segments[0].height_points.length',context),3));
w.document.querySelector('#undoEdit').click();
check('freeze undo restores relative mode',()=>assert.equal(vm.runInContext('draft.segments[0].mode',context),'ground'));
w.document.querySelector('[data-select-seg="0"]').click();
w.document.querySelector('[data-select-seg="2"]').dispatchEvent(new w.MouseEvent('click',{bubbles:true,shiftKey:true}));
check('shift range multiselect',()=>assert.equal(vm.runInContext('selectedSegments.size',context),3));
w.document.querySelector('#applyHeightMode').click();
check('batch absolute mode initializes start field',()=>{assert.equal(w.document.querySelector('[data-seg="0"][data-key="z_start"]').value,'100');assert.equal(vm.runInContext("draft.segments.every(s=>s.mode==='absolute')",context),true)});
w.document.querySelector('#uniformStart').value='90';w.document.querySelector('#uniformEnd').value='120';w.document.querySelector('#applyUniformGrade').click();
check('uniform grade follows cumulative lengths',()=>assert.equal(vm.runInContext('JSON.stringify(draft.segments.map(s=>[s.z_start,s.z_end]))',context),'[[90,100],[100,110],[110,120]]'));
w.document.querySelector('#undoEdit').click();
check('uniform grade undo',()=>assert.equal(vm.runInContext('draft.segments[0].z_start',context),100));

vm.runInContext("route={...route,start_station:{name:'S',center:300},stations:[{name:'A',center:1000},{name:'B',center:2000}]};state.service_direction='forward';state.start_station_id=-1;renderStartStations()",context);
check('start selector excludes forward terminal',()=>assert.deepEqual([...w.document.querySelector('#startStation').options].map(o=>o.textContent),['S','A']));
vm.runInContext("state.service_direction='backward';state.start_station_id=1;renderStartStations()",context);
check('start selector reverses station order',()=>assert.deepEqual([...w.document.querySelector('#startStation').options].map(o=>o.textContent),['B','A']));
vm.runInContext("state.can_continue=false;state.is_loop=true;update()",context);
check('continuation disabled before completion',()=>assert.equal(w.document.querySelector('#turnbackService').disabled,true));
vm.runInContext("state.can_continue=true;update()",context);
check('terminal offers turnback and loop continuation',()=>{assert.equal(w.document.querySelector('#turnbackService').disabled,false);assert.equal(w.document.querySelector('#nextLap').disabled,false)});
let sentService;w.fetch=async(url,options)=>{sentService={url,body:JSON.parse(options.body)};return{ok:false,json:async()=>({error:'request captured'})}};
w.document.querySelector('#startStation').value='0';await w.document.querySelector('#startFromStation').onclick();
check('selected middle station sent to server',()=>{assert.equal(sentService.body.start_station,0);assert.equal(sentService.body.direction,'backward')});
await w.document.querySelector('#nextLap').onclick();
check('next lap sends explicit continuation action',()=>{assert.equal(sentService.url,'/api/continue');assert.equal(sentService.body.action,'lap')});w.fetch=oldFetch;
console.log(`${count} DOM event checks passed`);
for(let i=0;i<30;i++)await Promise.resolve();await w.happyDOM.close();
